global:
  image: consul:1.8.0
  domain: consul
  datacenter: aws-us-east-1
  tls:
    enabled: false
  acls:
    manageSystemACLs: false
server:
  enabled: false
client:
  enabled: true
  join: ["provider=aws tag_key=Name tag_value=consul"]
connectInject:
  enabled: true
  default: true
  k8sAllowNamespaces: ["default"]
