---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        "consul.hashicorp.com/connect-service-upstreams": "api:9091:azure-us-west"
    spec:
      serviceAccountName: web
      containers:
      - name: web
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9090"
          - name: UPSTREAM_URIS
            value: "http://127.0.0.1:9091"
          - name: MESSAGE
            value: "Hello World"
          - name: NAME
            value: "web"
          - name: SERVER_TYPE
            value: "http"
          - name: TIMING_50_PERCENTILE
            value: "30ms"
          - name: TIMING_90_PERCENTILE
            value: "60ms"
          - name: TIMING_90_PERCENTILE
            value: "90ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger.service.consul:9411"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-traffic
  labels:
    app: web-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-traffic
  template:
    metadata:
      labels:
        app: web-traffic
    spec:
      containers:
      - name: load-test
        image: nicholasjackson/emojify-traffic:v0.2.1
        env:
        - name: BASE_URI
          value: http://web-load:9090
        - name: DURATION
          value: "24h"
        - name: SHOW_PROGRESS
          value: "false"
        - name: USERS
          value: "1"
