#external
---
apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    "consul.hashicorp.com/service-sync": "true"
    "consul.hashicorp.com/service-name": "web-lb"
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9090

#internal cluster IP for load simulator
---
apiVersion: v1
kind: Service
metadata:
  name: web-traffic
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
