---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        "consul.hashicorp.com/connect-service-upstreams": "cache:9092,currency:9093"
    spec:
      serviceAccountName: api
      containers:
      - name: api
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9091"
          - name: UPSTREAM_URIS
            value: "http://127.0.0.1:9092, http://127.0.0.1:9093"
          - name: MESSAGE
            value: "API response"
          - name: NAME
            value: "api"
          - name: SERVER_TYPE
            value: "http"
          - name: TIMING_50_PERCENTILE
            value: "20ms"
          - name: TIMING_90_PERCENTILE
            value: "10ms"
          - name: TIMING_90_PERCENTILE
            value: "40ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger.service.aws-us-east-1.consul:9411"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  labels:
    app: cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9901"
    spec:
      serviceAccountName: cache
      containers:
      - name: cache
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9092"
          - name: MESSAGE
            value: "Cache response"
          - name: NAME
            value: "cache"
          - name: SERVER_TYPE
            value: "http"
          - name: TIMING_50_PERCENTILE
            value: "1ms"
          - name: TIMING_90_PERCENTILE
            value: "2ms"
          - name: TIMING_90_PERCENTILE
            value: "1ms"
          - name: TIMING_VARIANCE
            value: "10"
          - name: TRACING_ZIPKIN
            value: "http://jaeger.service.aws-us-east-1.consul:9411"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currency

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9901"
    spec:
      serviceAccountName: currency
      containers:
      - name: currency
        image: "nicholasjackson/fake-service:v0.7.8"
        imagePullPolicy: Always
        ports:
        - containerPort: 9093
        env:
          - name: LISTEN_ADDR
            value: "0.0.0.0:9093"
          - name: UPSTREAM_URIS
            value:
          - name: MESSAGE
            value: "Currency response"
          - name: NAME
            value: "currency"
          - name: SERVER_TYPE
            value: "http"
          - name: ERROR_RATE
            value: "0.0"
          - name: ERROR_CODE
            value: "500"
          - name: ERROR_TYPE
            value: "http_error"
          - name: TRACING_ZIPKIN
            value: "http://jaeger.service.aws-us-east-1.consul:9411"
